# Generated by Django 4.2.9 on 2024-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotesApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="file_upload",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
