# Generated by Django 4.2.9 on 2024-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotesApp", "0002_notes_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("0", "Select File Type"),
                    ("IMG", "IMAGE"),
                    ("TXT", "TEXT"),
                    ("PDF", "PDF"),
                    ("VID", "VID"),
                    ("DEF", "DEFAULT"),
                ],
                default="0",
                max_length=10,
            ),
        ),
    ]
