# Generated by Django 4.2.9 on 2024-02-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotesApp", "0003_notes_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes", name="dislike", field=models.IntegerField(default="0"),
        ),
        migrations.AddField(
            model_name="notes", name="like", field=models.IntegerField(default="0"),
        ),
    ]
