# Generated by Django 4.2.9 on 2024-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotesApp", "0004_notes_dislike_notes_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("IMG", "IMAGE"),
                    ("TXT", "TEXT"),
                    ("PDF", "PDF"),
                    ("VID", "VIDEO"),
                    ("DEF", "DEFAULT"),
                ],
                default="0",
                max_length=10,
            ),
        ),
    ]
