# Generated by Django 4.2.9 on 2024-03-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NotesApp", "0007_remainder_sid"),
    ]

    operations = [
        migrations.RemoveField(model_name="remainder", name="sid",),
    ]
