# Generated by Django 4.2.9 on 2024-03-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NotesApp", "0008_remove_remainder_sid"),
    ]

    operations = [
        migrations.RemoveField(model_name="notes", name="file_type",),
        migrations.RemoveField(model_name="notes", name="file_upload",),
        migrations.AlterField(
            model_name="notes", name="dislike", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="notes", name="like", field=models.IntegerField(),
        ),
    ]
